[package]
name = "world-chain-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# reth
reth-node-optimism = { git = "https://github.com/paradigmxyz/reth", version = "1.0.6", features = [
    "optimism",
] }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", version = "1.0.6", features = [
    "optimism",
] }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", version = "1.0.6" }


# other
clap = { version = "4", features = ["derive", "env"] }


[[bin]]
name = "builder"
path = "bin/builder.rs"
